trigger:
  - master

jobs:
- job: myJob
  timeoutInMinutes: 240
  
  pool:
    name: $(Agent.Name)

  steps:
  - script: env
    displayName: 'Print environment'

  - bash: scripts/cluster_upgrade.sh
    displayName: 'Upgrade cluster'
