trigger:
- master

pool:
  name: $(Agent.Name)

steps:
- script: env
  displayName: 'Print environment'

- bash: scripts/ensure_deps.sh
  displayName: 'Ensure dependencies'

- bash: scripts/cluster_definition.sh
  displayName: 'Create cluster definition'

- bash: scripts/cluster_deploy.sh
  displayName: 'Deploy cluster'

- bash: scripts/prometheus_deploy.sh
  displayName: 'Deploy Prometheus & Grafana if requested'  