jobs:
- job: myJob
  timeoutInMinutes: 120
  
  trigger:
  - master

  pool:
    name: 'shanghai-akse'

  steps:
  - script: env
    displayName: 'Print environment'

  - bash: scripts/cluster_upgrade.sh
    displayName: 'Upgrade cluster'
